// Pack generation system for MTG-style idea cards
import { createClient } from '@supabase/supabase-js';
import { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, OPENAI_API_KEY } from '$env/static/private';

// Validate environment variables
if (!SUPABASE_URL) {
  throw new Error('SUPABASE_URL environment variable is required');
}
if (!SUPABASE_SERVICE_ROLE_KEY) {
  throw new Error('SUPABASE_SERVICE_ROLE_KEY environment variable is required');
}
if (!OPENAI_API_KEY) {
  throw new Error('OPENAI_API_KEY environment variable is required');
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

// Rarity distribution weights (percentages)
const RARITY_DISTRIBUTION = {
  common: 65,    // 65% - abundant, wide-scope ideas
  special: 22,   // 22% - refined, contextual ideas
  rare: 10,      // 10% - high-quality, connected ideas
  legendary: 3   // 3% - revelatory, cross-connected insights
};

// Pack composition rules
const PACK_RULES = {
  minCards: 3,
  maxCards: 5,  // Reduced from 7 to 5 for more balanced packs
  maxLegendary: 1,  // Never more than 1 legendary per pack
  legendaryChance: 0.05,  // 5% chance of legendary in any pack (much rarer!)
  rareChance: 0.25,  // 25% chance of rare in any pack
  specialChance: 0.60,  // 60% chance of special in any pack
  commonChance: 1.0  // 100% chance of common cards (always get some)
};

/**
 * Generate a pack of idea cards based on a prompt
 * @param {string} prompt - The prompt to generate ideas from
 * @param {string} worldId - The world/project ID
 * @param {string} userId - The user ID
 * @param {Object} context - Additional context (existing cards, world info, etc.)
 * @returns {Promise<Array>} Array of generated cards with rarity
 */
export async function generatePack(prompt, worldId, userId, context = {}) {
  try {
    console.log('🎲 Starting pack generation for user:', userId, 'world:', worldId);
    
    // Step 1: Generate raw ideas from AI
    console.log('🎲 Step 1: Generating raw ideas...');
    const rawIdeas = await generateRawIdeas(prompt, context);
    console.log('🎲 Generated', rawIdeas.length, 'raw ideas');
    
    if (rawIdeas.length === 0) {
      throw new Error('No ideas were generated by the AI');
    }
    
    // Step 2: Assign rarities based on quality and context
    console.log('🎲 Step 2: Assigning rarities...');
    const ideasWithRarity = await assignRarities(rawIdeas, worldId, userId, context);
    console.log('🎲 Assigned rarities to', ideasWithRarity.length, 'ideas');
    
    // Step 3: Apply pack composition rules
    console.log('🎲 Step 3: Applying pack rules...');
    const packCards = applyPackRules(ideasWithRarity);
    console.log('🎲 Final pack contains', packCards.length, 'cards');
    
    // Step 4: Save cards to database
    console.log('🎲 Step 4: Saving cards to database...');
    const savedCards = await savePackCards(packCards, worldId, userId);
    console.log('🎲 Successfully saved', savedCards.length, 'cards');
    
    return savedCards;
  } catch (error) {
    console.error('🎲 Error generating pack:', error);
    // Re-throw with more context
    if (error.message.includes('OpenAI API error')) {
      throw new Error(`AI generation failed: ${error.message}`);
    } else if (error.message.includes('Failed to save pack cards')) {
      throw new Error(`Database error: ${error.message}`);
    } else {
      throw new Error(`Pack generation failed: ${error.message}`);
    }
  }
}

/**
 * Generate raw ideas from AI models with rarity-based quality
 * @param {string} prompt - The prompt
 * @param {Object} context - Additional context
 * @returns {Promise<Array>} Array of raw idea objects
 */
async function generateRawIdeas(prompt, context) {
  // Use different AI models based on context and tier
  const modelKey = context.userTier >= 2 ? 'gpt-4o' : 'gpt-3.5-turbo';
  
  // Generate ideas for each rarity tier separately
  const allIdeas = [];
  
  // Generate Common ideas (fast, wide-scope)
  const commonIdeas = await generateIdeasByRarity(prompt, context, 'common', modelKey);
  allIdeas.push(...commonIdeas);
  
  // Generate Special ideas (refined, contextual)
  const specialIdeas = await generateIdeasByRarity(prompt, context, 'special', modelKey);
  allIdeas.push(...specialIdeas);
  
  // Generate Rare ideas (high-quality, connected)
  const rareIdeas = await generateIdeasByRarity(prompt, context, 'rare', modelKey);
  allIdeas.push(...rareIdeas);
  
  // Generate Legendary ideas (transformative, revelatory)
  const legendaryIdeas = await generateIdeasByRarity(prompt, context, 'legendary', modelKey);
  allIdeas.push(...legendaryIdeas);
  
  return allIdeas;
}

/**
 * Generate ideas for a specific rarity tier
 * @param {string} prompt - The prompt
 * @param {Object} context - Additional context
 * @param {string} rarity - The rarity tier
 * @param {string} modelKey - AI model to use
 * @returns {Promise<Array>} Array of ideas for this rarity
 */
async function generateIdeasByRarity(prompt, context, rarity, modelKey) {
  // Build context information for the AI
  let contextInfo = '';
  if (context.existingCards && context.existingCards.length > 0) {
    contextInfo = `\n\nEXISTING CARDS IN THIS PROJECT (to avoid duplicating and to build upon):
${context.existingCards.map(card => `- "${card.title}": ${card.content?.substring(0, 100)}...`).join('\n')}

IMPORTANT: Do NOT create cards that are duplicates or very similar to the existing cards above. Instead, create NEW and DIFFERENT ideas that complement or expand upon the existing content.`;
  }

  const rarityPrompts = {
    common: {
      system: `You are Mr. Wiskr, a mysterious card dealer from the void who crafts idea cards for creative souls. Generate COMMON ideas - these should be:
- Fast, accessible, and immediately useful
- Broad in scope and widely applicable
- Straightforward and easy to understand
- Good starting points that can be developed further
- Practical and actionable
- DIRECTLY RELATED to the user's prompt and existing project content

These are the everyday tools of creation - solid, reliable, and always useful.

CRITICAL: You MUST read and understand the existing cards below. If the user mentions a character name (like "Scarlett"), you MUST reference that character specifically in your ideas. Do NOT create generic ideas that could apply to any character or project.

Generate 4-5 common ideas that are solid but not extraordinary, and that are SPECIFICALLY relevant to the user's request and existing project content.${contextInfo}

IMPORTANT: Return your response as a JSON array of objects. Each object should have:
- "title": A short, descriptive title for the idea
- "content": The full idea description (2-3 sentences)
- "tags": An array of relevant tags

Example format:
[
  {
    "title": "Basic Character Development",
    "content": "Create a simple character questionnaire to help develop basic personality traits, motivations, and background details for your protagonist.",
    "tags": ["character", "development", "writing"]
  }
]`,
      user: prompt
    },
    
    special: {
      system: `You are Mr. Wiskr, a mysterious card dealer from the void who crafts idea cards for creative souls. Generate SPECIAL ideas - these should be:
- More refined and thoughtful than common ideas
- Show deeper understanding of the prompt
- Offer unique angles or perspectives
- Have clear creative potential
- Be more specific and well-developed
- DIRECTLY RELATED to the user's prompt and existing project content

These are the refined tools of creation - crafted with care and insight, offering something beyond the ordinary.

CRITICAL: You MUST read and understand the existing cards below. If the user mentions a character name (like "Scarlett"), you MUST reference that character specifically in your ideas. Do NOT create generic ideas that could apply to any character or project.

Generate 2-3 special ideas that stand out from the ordinary, and that are SPECIFICALLY relevant to the user's request and existing project content.${contextInfo}

IMPORTANT: Return your response as a JSON array of objects. Each object should have:
- "title": A short, descriptive title for the idea
- "content": The full idea description (3-4 sentences)
- "tags": An array of relevant tags

Example format:
[
  {
    "title": "Emotional Arc Mapping",
    "content": "Design a visual emotional journey map that tracks your character's psychological state throughout the story, using color coding and intensity markers to show how their feelings evolve and impact their decisions.",
    "tags": ["character", "emotion", "plotting", "visual"]
  }
]`,
      user: prompt
    },
    
    rare: {
      system: `You are Mr. Wiskr, a mysterious card dealer from the void who crafts idea cards for creative souls. Generate RARE ideas - these should be:
- High-quality and deeply insightful
- Show sophisticated creative thinking
- Connect multiple concepts in interesting ways
- Offer surprising but logical developments
- Be well-crafted and memorable
- DIRECTLY RELATED to the user's prompt and existing project content

These are the precious gems of creation - rare insights that spark new ways of thinking and seeing.

CRITICAL: You MUST read and understand the existing cards below. If the user mentions a character name (like "Scarlett"), you MUST reference that character specifically in your ideas. Do NOT create generic ideas that could apply to any character or project.

Generate 1-2 rare ideas that demonstrate exceptional creative thinking, and that are SPECIFICALLY relevant to the user's request and existing project content.${contextInfo}

IMPORTANT: Return your response as a JSON array of objects. Each object should have:
- "title": A short, descriptive title for the idea
- "content": The full idea description (4-5 sentences)
- "tags": An array of relevant tags

Example format:
[
  {
    "title": "Metaphorical World-Building",
    "content": "Create a story world where the physical environment directly reflects and amplifies your protagonist's internal psychological state, with weather patterns, architecture, and natural phenomena that shift and evolve as the character grows and changes throughout their journey.",
    "tags": ["worldbuilding", "psychology", "metaphor", "character", "setting"]
  }
]`,
      user: prompt
    },
    
    legendary: {
      system: `You are Mr. Wiskr, a mysterious card dealer from the void who crafts idea cards for creative souls. Generate a LEGENDARY idea - this should be:
- Transformative and revelatory
- Completely unexpected yet perfect
- Show profound understanding and creativity
- Connect disparate elements in brilliant ways
- Be the kind of idea that changes everything
- Feel like a breakthrough or epiphany
- DIRECTLY RELATED to the user's prompt and existing project content

These are the legendary artifacts of creation - ideas that transcend the ordinary and reshape reality itself. Such cards are rare indeed, forged in the deepest reaches of the creative void.

CRITICAL: You MUST read and understand the existing cards below. If the user mentions a character name (like "Scarlett"), you MUST reference that character specifically in your ideas. Do NOT create generic ideas that could apply to any character or project.

Generate 1 legendary idea that is truly extraordinary and game-changing, and that is SPECIFICALLY relevant to the user's request and existing project content.${contextInfo}

IMPORTANT: Return your response as a JSON array of objects. Each object should have:
- "title": A short, descriptive title for the idea
- "content": The full idea description (5-6 sentences)
- "tags": An array of relevant tags

Example format:
[
  {
    "title": "Temporal Narrative Architecture",
    "content": "Design a story structure where time itself becomes a character, with past, present, and future events existing simultaneously in a quantum narrative state where the reader's attention and emotional investment literally shapes which timeline becomes 'real' in the story, creating a meta-commentary on how stories create reality through collective belief and engagement.",
    "tags": ["structure", "time", "meta", "quantum", "reality", "narrative"]
  }
]`,
      user: prompt
    }
  };

  const config = rarityPrompts[rarity];
  if (!config) return [];

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${OPENAI_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: modelKey,
      messages: [
        { role: 'system', content: config.system },
        { role: 'user', content: config.user }
      ],
      temperature: rarity === 'legendary' ? 0.9 : 0.8, // Higher creativity for legendary
      max_tokens: rarity === 'legendary' ? 1000 : 800
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error(`Failed to generate ${rarity} ideas:`, response.status, errorText);
    throw new Error(`OpenAI API error (${response.status}): ${errorText}`);
  }

  const data = await response.json();
  const content = data.choices[0].message.content;
  
  try {
    // Try to parse as JSON first
    const ideas = JSON.parse(content);
    if (!Array.isArray(ideas)) {
      throw new Error('Response is not an array');
    }
    
    // Add rarity metadata to each idea
    return ideas.map(idea => ({
      ...idea,
      _generatedRarity: rarity
    }));
  } catch (parseError) {
    console.error(`Failed to parse ${rarity} ideas as JSON:`, content);
    
    // Fallback: try to extract ideas from text format
    try {
      const fallbackIdeas = parseTextIdeas(content, rarity);
      if (fallbackIdeas.length > 0) {
        console.log(`Successfully parsed ${fallbackIdeas.length} ${rarity} ideas using fallback parser`);
        return fallbackIdeas;
      }
    } catch (fallbackError) {
      console.error(`Fallback parsing also failed for ${rarity} ideas:`, fallbackError);
    }
    
    return [];
  }
}

/**
 * Fallback parser for when AI returns text instead of JSON
 * @param {string} content - Raw AI response text
 * @param {string} rarity - The rarity tier
 * @returns {Array} Array of parsed ideas
 */
function parseTextIdeas(content, rarity) {
  const ideas = [];
  
  // Try to extract numbered or bulleted ideas
  const lines = content.split('\n').filter(line => line.trim());
  
  for (const line of lines) {
    // Look for patterns like "1. Title: Description" or "- Title: Description"
    const match = line.match(/^[\d\-•]\s*(.+?):\s*(.+)$/);
    if (match) {
      const title = match[1].trim();
      const description = match[2].trim();
      
      if (title && description) {
        ideas.push({
          title: title,
          content: description,
          tags: [rarity, 'parsed'],
          _generatedRarity: rarity
        });
      }
    }
  }
  
  // If no structured format found, try to split by paragraphs
  if (ideas.length === 0) {
    const paragraphs = content.split('\n\n').filter(p => p.trim().length > 20);
    paragraphs.forEach((paragraph, index) => {
      const sentences = paragraph.split('. ');
      const title = sentences[0]?.substring(0, 50) + (sentences[0]?.length > 50 ? '...' : '');
      const content = paragraph.trim();
      
      if (title && content) {
        ideas.push({
          title: title,
          content: content,
          tags: [rarity, 'parsed'],
          _generatedRarity: rarity
        });
      }
    });
  }
  
  return ideas;
}

/**
 * Assign rarities to ideas based on quality and context
 * @param {Array} ideas - Raw ideas with pre-generated rarities
 * @param {string} worldId - World ID
 * @param {string} userId - User ID
 * @param {Object} context - Additional context
 * @returns {Promise<Array>} Ideas with assigned rarities
 */
async function assignRarities(ideas, worldId, userId, context) {
  const ideasWithRarity = [];
  
  for (const idea of ideas) {
    // Use the pre-generated rarity from the AI generation
    const rarity = idea._generatedRarity || 'common';
    
    // Remove the metadata field
    const { _generatedRarity, ...cleanIdea } = idea;
    
    ideasWithRarity.push({
      ...cleanIdea,
      rarity,
      progress: 1, // All new cards start as Raw (1 star)
      mana_cost: 1, // Must be >= 1 due to database constraint
      pinned: false,
      created_at: new Date().toISOString()
    });
  }
  
  return ideasWithRarity;
}

/**
 * Analyze the quality and relevance of an idea
 * @param {Object} idea - The idea to analyze
 * @param {string} worldId - World ID
 * @param {Object} context - Additional context
 * @returns {Promise<number>} Quality score (0-100)
 */
async function analyzeIdeaQuality(idea, worldId, context) {
  let score = 50; // Base score
  
  // Check for existing similar ideas (uniqueness)
  const { data: similarIdeas } = await supabase
    .from('cards')
    .select('content, tags')
    .eq('project_id', worldId)
    .ilike('content', `%${idea.title}%`);
  
  if (similarIdeas && similarIdeas.length === 0) {
    score += 15; // Bonus for uniqueness
  }
  
  // Analyze content depth and specificity
  if (idea.content && idea.content.length > 100) {
    score += 10; // Bonus for detailed content
  }
  
  // Check for multiple relevant tags
  if (idea.tags && idea.tags.length >= 3) {
    score += 10; // Bonus for well-tagged ideas
  }
  
  // Check for creative keywords that suggest higher quality
  const creativeKeywords = ['unique', 'innovative', 'unexpected', 'surprising', 'deep', 'complex', 'layered'];
  const hasCreativeKeywords = creativeKeywords.some(keyword => 
    idea.content.toLowerCase().includes(keyword) || 
    idea.title.toLowerCase().includes(keyword)
  );
  
  if (hasCreativeKeywords) {
    score += 15; // Bonus for creative language
  }
  
  // Add some randomness to make packs feel varied
  const randomFactor = Math.random() * 20 - 10; // -10 to +10
  score += randomFactor;
  
  return Math.max(0, Math.min(100, score));
}

/**
 * Determine rarity based on quality score
 * @param {number} score - Quality score (0-100)
 * @returns {string} Rarity level
 */
function determineRarity(score) {
  if (score >= 85) return 'legendary';
  if (score >= 70) return 'rare';
  if (score >= 50) return 'special';
  return 'common';
}

/**
 * Apply pack composition rules with proper probability-based distribution
 * @param {Array} ideasWithRarity - Ideas with assigned rarities
 * @returns {Array} Final pack composition
 */
function applyPackRules(ideasWithRarity) {
  let pack = [...ideasWithRarity];
  
  // Group ideas by rarity
  const byRarity = {
    common: pack.filter(card => card.rarity === 'common'),
    special: pack.filter(card => card.rarity === 'special'),
    rare: pack.filter(card => card.rarity === 'rare'),
    legendary: pack.filter(card => card.rarity === 'legendary')
  };
  
  const finalPack = [];
  
  // Determine pack composition based on probabilities
  // More balanced distribution: 33% chance each for 3, 4, or 5 cards
  const packSizeRoll = Math.random();
  let packSize;
  if (packSizeRoll < 0.33) {
    packSize = 3;
  } else if (packSizeRoll < 0.66) {
    packSize = 4;
  } else {
    packSize = 5;
  }
  
  // Step 1: Check for legendary (5% chance)
  if (Math.random() < PACK_RULES.legendaryChance && byRarity.legendary.length > 0) {
    finalPack.push(byRarity.legendary[0]);
  }
  
  // Step 2: Check for rare (25% chance, but only if we don't have legendary or have room)
  if (Math.random() < PACK_RULES.rareChance && byRarity.rare.length > 0 && finalPack.length < packSize) {
    const rareCount = Math.random() < 0.3 ? 2 : 1; // 30% chance of 2 rares, 70% chance of 1
    const actualRareCount = Math.min(rareCount, byRarity.rare.length, packSize - finalPack.length);
    finalPack.push(...byRarity.rare.slice(0, actualRareCount));
  }
  
  // Step 3: Add special cards (60% chance, but more likely if we have room)
  const specialRoll = Math.random();
  if (specialRoll < PACK_RULES.specialChance && byRarity.special.length > 0 && finalPack.length < packSize) {
    const specialCount = specialRoll < 0.2 ? 2 : 1; // 20% chance of 2 specials, 80% chance of 1
    const actualSpecialCount = Math.min(specialCount, byRarity.special.length, packSize - finalPack.length);
    finalPack.push(...byRarity.special.slice(0, actualSpecialCount));
  }
  
  // Step 4: Fill remaining slots with common cards (always get some commons)
  const remainingSlots = packSize - finalPack.length;
  if (remainingSlots > 0 && byRarity.common.length > 0) {
    const commonCount = Math.min(remainingSlots, byRarity.common.length);
    finalPack.push(...byRarity.common.slice(0, commonCount));
  }
  
  // Step 5: If we don't have enough cards, adjust pack size instead of adding fallbacks
  if (finalPack.length < PACK_RULES.minCards) {
    // If we have at least 1 card, that's better than a generic fallback
    if (finalPack.length > 0) {
      // Keep what we have - quality over quantity
      console.log(`🎲 Pack has ${finalPack.length} cards (less than minimum ${PACK_RULES.minCards}, but avoiding generic fallbacks)`);
    } else {
      // Only create fallback if we have absolutely no cards
      finalPack.push(createFallbackCard());
    }
  }
  
  // Step 6: Shuffle the pack to randomize order (except keep legendary at end for dramatic effect)
  const legendaryCards = finalPack.filter(card => card.rarity === 'legendary');
  const nonLegendaryCards = finalPack.filter(card => card.rarity !== 'legendary');
  
  // Shuffle non-legendary cards
  for (let i = nonLegendaryCards.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [nonLegendaryCards[i], nonLegendaryCards[j]] = [nonLegendaryCards[j], nonLegendaryCards[i]];
  }
  
  // Combine shuffled cards with legendary at the end
  return [...nonLegendaryCards, ...legendaryCards];
}

/**
 * Save pack cards to database
 * @param {Array} packCards - Cards to save
 * @param {string} worldId - World ID
 * @param {string} userId - User ID
 * @returns {Promise<Array>} Saved cards with IDs
 */
async function savePackCards(packCards, worldId, userId) {
  // Check for duplicates before saving
  const filteredCards = await filterDuplicateCards(packCards, worldId, userId);
  
  if (filteredCards.length === 0) {
    return [];
  }
  
  const cardsToInsert = filteredCards.map(card => ({
    project_id: worldId,
    user_id: userId,
    title: card.title,
    content: card.content,
    tags: card.tags,
    rarity: card.rarity,
    progress: card.progress,
    mana_cost: card.mana_cost,
    art_url: card.art_url,
    pinned: card.pinned,
    created_at: card.created_at
  }));
  
  const { data, error } = await supabase
    .from('cards')
    .insert(cardsToInsert)
    .select();
  
  if (error) {
    console.error('Error saving pack cards:', error);
    throw new Error('Failed to save pack cards');
  }
  
  return data;
}

/**
 * Filter out duplicate cards before saving
 * @param {Array} packCards - Cards to check for duplicates
 * @param {string} worldId - World ID
 * @param {string} userId - User ID
 * @returns {Promise<Array>} Filtered cards without duplicates
 */
async function filterDuplicateCards(packCards, worldId, userId) {
  // Get existing cards in the project
  const { data: existingCards } = await supabase
    .from('cards')
    .select('title, content')
    .eq('project_id', worldId)
    .eq('user_id', userId);
  
  if (!existingCards || existingCards.length === 0) {
    return packCards; // No existing cards, so no duplicates possible
  }
  
  const filteredCards = [];
  
  for (const newCard of packCards) {
    let isDuplicate = false;
    
    // Check for title similarity (exact match or very similar)
    for (const existingCard of existingCards) {
      if (newCard.title.toLowerCase().trim() === existingCard.title.toLowerCase().trim()) {
        isDuplicate = true;
        break;
      }
      
      // Check for content similarity (if content is very similar, it's likely a duplicate)
      if (newCard.content && existingCard.content) {
        const newContent = newCard.content.toLowerCase().trim();
        const existingContent = existingCard.content.toLowerCase().trim();
        
        // Check for exact content match first
        if (newContent === existingContent) {
          isDuplicate = true;
          break;
        }
        
        // Check for high similarity (lowered threshold to catch more duplicates)
        const similarity = calculateSimilarity(newContent, existingContent);
        if (similarity > 0.7) { // Lowered from 0.8 to 0.7
          isDuplicate = true;
          break;
        }
        
        // Check for title similarity (if titles are very similar, likely duplicates)
        const titleSimilarity = calculateSimilarity(newCard.title.toLowerCase(), existingCard.title.toLowerCase());
        if (titleSimilarity > 0.8) {
          isDuplicate = true;
          break;
        }
      }
    }
    
    if (!isDuplicate) {
      filteredCards.push(newCard);
    }
  }
  
  return filteredCards;
}

/**
 * Calculate similarity between two strings (simple Jaccard similarity)
 * @param {string} str1 - First string
 * @param {string} str2 - Second string
 * @returns {number} Similarity score (0-1)
 */
function calculateSimilarity(str1, str2) {
  const words1 = new Set(str1.split(/\s+/));
  const words2 = new Set(str2.split(/\s+/));
  
  const intersection = new Set([...words1].filter(x => words2.has(x)));
  const union = new Set([...words1, ...words2]);
  
  return intersection.size / union.size;
}

/**
 * Create fallback ideas when AI parsing fails
 * @param {string} content - Raw AI content
 * @returns {Array} Fallback ideas
 */
function createFallbackIdeas(content) {
  // Simple fallback: split content into sentences and create basic ideas
  const sentences = content.split(/[.!?]+/).filter(s => s.trim().length > 10);
  
  return sentences.slice(0, 5).map((sentence, index) => ({
    title: `Idea ${index + 1}`,
    content: sentence.trim(),
    tags: ['generated', 'idea'],
    type: 'other'
  }));
}

/**
 * Create a fallback card for pack completion (only used in extreme cases)
 * @returns {Object} Fallback card
 */
function createFallbackCard() {
  const fallbackTitles = [
    'Creative Spark',
    'New Perspective',
    'Fresh Angle',
    'Alternative Approach',
    'Different Viewpoint'
  ];
  
  const fallbackContent = [
    'A new way of thinking about your creative project that opens up fresh possibilities.',
    'An alternative perspective that could lead to unexpected breakthroughs in your work.',
    'A different angle on your creative challenge that might reveal hidden opportunities.',
    'A fresh approach to your project that could spark new ideas and directions.',
    'A new viewpoint that might help you see your creative work from a different lens.'
  ];
  
  const randomIndex = Math.floor(Math.random() * fallbackTitles.length);
  
  return {
    title: fallbackTitles[randomIndex],
    content: fallbackContent[randomIndex],
    tags: ['creative', 'inspiration', 'fallback'],
    type: 'other',
    rarity: 'common',
    progress: 1,
    mana_cost: 1, // Must be >= 1 due to database constraint
    pinned: false,
    created_at: new Date().toISOString()
  };
}
